/**
* Copyright (C) 2011，光庭汽车电子有限公司(http://www.kotei.com.cn)
* All rights reserved.
* 
* 文件名称：gettext.h -- gettext
* 摘    要：该文件的主要内容为多语言翻译功能
*
* 当前版本：1.0
* 作    者：昌敦雄
* 创建日期：2011年6月14日
*
* 修改历史：
* [修改序列]   [修改日期]    [修改者]     [修改内容]
*    1         2011-06-14     昌敦雄      1.0.0版本的内容声明
* 
**/

#ifndef __GETTEXT_H__
#define __GETTEXT_H__

#if defined(WIN32) || defined(_WIN32) || defined(__WIN32__) || defined(__NT__) ||  defined(_WIN32_WCE) || defined(WINCE)
#	ifdef GETTEXT_EXPROT
#		define GETTEXT_API	__declspec(dllexport)
#	else
#		define GETTEXT_API	__declspec(dllimport)
#	endif
#else
#	ifdef GETTEXT_EXPROT
#		define GETTEXT_API	
#	else
#		define GETTEXT_API	extern
#	endif
#endif

#ifndef TCHAR
#	if defined(_UNICODE) || defined(UNICODE)
#		define TCHAR wchar_t
#	else
#		define TCHAR char
#	endif
#endif

#if defined(_UNICODE) || defined(UNICODE)
#define _(STRING)	gettext(L##STRING)
#else
#define _(STRING)	gettext(STRING)
#endif

#define __(T_STRING)	gettext(T_STRING)

#ifdef __cplusplus
extern "C" {
	namespace GETTEXT {
#endif

		// 多语言类型
		typedef enum LANGUAGE_TYPE
		{
			wxLANGUAGE_ABKHAZIAN = 0,
			wxLANGUAGE_AFAR,
			wxLANGUAGE_AFRIKAANS,
			wxLANGUAGE_ALBANIAN,
			wxLANGUAGE_AMHARIC,
			wxLANGUAGE_ARABIC,
			wxLANGUAGE_ARABIC_ALGERIA,
			wxLANGUAGE_ARABIC_BAHRAIN,
			wxLANGUAGE_ARABIC_EGYPT,
			wxLANGUAGE_ARABIC_IRAQ,
			wxLANGUAGE_ARABIC_JORDAN,
			wxLANGUAGE_ARABIC_KUWAIT,
			wxLANGUAGE_ARABIC_LEBANON,
			wxLANGUAGE_ARABIC_LIBYA,
			wxLANGUAGE_ARABIC_MOROCCO,
			wxLANGUAGE_ARABIC_OMAN,
			wxLANGUAGE_ARABIC_QATAR,
			wxLANGUAGE_ARABIC_SAUDI_ARABIA,
			wxLANGUAGE_ARABIC_SUDAN,
			wxLANGUAGE_ARABIC_SYRIA,
			wxLANGUAGE_ARABIC_TUNISIA,
			wxLANGUAGE_ARABIC_UAE,
			wxLANGUAGE_ARABIC_YEMEN,
			wxLANGUAGE_ARMENIAN,
			wxLANGUAGE_ASSAMESE,
			wxLANGUAGE_ASTURIAN,
			wxLANGUAGE_AYMARA,
			wxLANGUAGE_AZERI,
			wxLANGUAGE_AZERI_CYRILLIC,
			wxLANGUAGE_AZERI_LATIN,
			wxLANGUAGE_BASHKIR,
			wxLANGUAGE_BASQUE,
			wxLANGUAGE_BELARUSIAN,
			wxLANGUAGE_BENGALI,
			wxLANGUAGE_BHUTANI,
			wxLANGUAGE_BIHARI,
			wxLANGUAGE_BISLAMA,
			wxLANGUAGE_BOSNIAN,
			wxLANGUAGE_BRETON,
			wxLANGUAGE_BULGARIAN,
			wxLANGUAGE_BURMESE,
			wxLANGUAGE_CAMBODIAN,
			wxLANGUAGE_CATALAN,
			wxLANGUAGE_CHINESE,
			wxLANGUAGE_CHINESE_SIMPLIFIED,
			wxLANGUAGE_CHINESE_TRADITIONAL,
			wxLANGUAGE_CHINESE_HONGKONG,
			wxLANGUAGE_CHINESE_MACAU,
			wxLANGUAGE_CHINESE_SINGAPORE,
			wxLANGUAGE_CHINESE_TAIWAN,
			wxLANGUAGE_CORSICAN,
			wxLANGUAGE_CROATIAN,
			wxLANGUAGE_CZECH,
			wxLANGUAGE_DANISH,
			wxLANGUAGE_DUTCH,
			wxLANGUAGE_DUTCH_BELGIAN,
			wxLANGUAGE_ENGLISH,
			wxLANGUAGE_ENGLISH_UK,
			wxLANGUAGE_ENGLISH_US,
			wxLANGUAGE_ENGLISH_AUSTRALIA,
			wxLANGUAGE_ENGLISH_BELIZE,
			wxLANGUAGE_ENGLISH_BOTSWANA,
			wxLANGUAGE_ENGLISH_CANADA,
			wxLANGUAGE_ENGLISH_CARIBBEAN,
			wxLANGUAGE_ENGLISH_DENMARK,
			wxLANGUAGE_ENGLISH_EIRE,
			wxLANGUAGE_ENGLISH_JAMAICA,
			wxLANGUAGE_ENGLISH_NEW_ZEALAND,
			wxLANGUAGE_ENGLISH_PHILIPPINES,
			wxLANGUAGE_ENGLISH_SOUTH_AFRICA,
			wxLANGUAGE_ENGLISH_TRINIDAD,
			wxLANGUAGE_ENGLISH_ZIMBABWE,
			wxLANGUAGE_ESPERANTO,
			wxLANGUAGE_ESTONIAN,
			wxLANGUAGE_FAEROESE,
			wxLANGUAGE_FARSI,
			wxLANGUAGE_FIJI,
			wxLANGUAGE_FINNISH,
			wxLANGUAGE_FRENCH,
			wxLANGUAGE_FRENCH_BELGIAN,
			wxLANGUAGE_FRENCH_CANADIAN,
			wxLANGUAGE_FRENCH_LUXEMBOURG,
			wxLANGUAGE_FRENCH_MONACO,
			wxLANGUAGE_FRENCH_SWISS,
			wxLANGUAGE_FRISIAN,
			wxLANGUAGE_GALICIAN,
			wxLANGUAGE_GEORGIAN,
			wxLANGUAGE_GERMAN,
			wxLANGUAGE_GERMAN_AUSTRIAN,
			wxLANGUAGE_GERMAN_BELGIUM,
			wxLANGUAGE_GERMAN_LIECHTENSTEIN,
			wxLANGUAGE_GERMAN_LUXEMBOURG,
			wxLANGUAGE_GERMAN_SWISS,
			wxLANGUAGE_GREEK,
			wxLANGUAGE_GREENLANDIC,
			wxLANGUAGE_GUARANI,
			wxLANGUAGE_GUJARATI,
			wxLANGUAGE_HAUSA,
			wxLANGUAGE_HEBREW,
			wxLANGUAGE_HINDI,
			wxLANGUAGE_HUNGARIAN,
			wxLANGUAGE_ICELANDIC,
			wxLANGUAGE_INDONESIAN,
			wxLANGUAGE_INTERLINGUA,
			wxLANGUAGE_INTERLINGUE,
			wxLANGUAGE_INUKTITUT,
			wxLANGUAGE_INUPIAK,
			wxLANGUAGE_IRISH,
			wxLANGUAGE_ITALIAN,
			wxLANGUAGE_ITALIAN_SWISS,
			wxLANGUAGE_JAPANESE,
			wxLANGUAGE_JAVANESE,
			wxLANGUAGE_KANNADA,
			wxLANGUAGE_KASHMIRI,
			wxLANGUAGE_KASHMIRI_INDIA,
			wxLANGUAGE_KAZAKH,
			wxLANGUAGE_KERNEWEK,
			wxLANGUAGE_KINYARWANDA,
			wxLANGUAGE_KIRGHIZ,
			wxLANGUAGE_KIRUNDI,
			wxLANGUAGE_KONKANI,
			wxLANGUAGE_KOREAN,
			wxLANGUAGE_KURDISH,
			wxLANGUAGE_LAOTHIAN,
			wxLANGUAGE_LATIN,
			wxLANGUAGE_LATVIAN,
			wxLANGUAGE_LINGALA,
			wxLANGUAGE_LITHUANIAN,
			wxLANGUAGE_MACEDONIAN,
			wxLANGUAGE_MALAGASY,
			wxLANGUAGE_MALAY,
			wxLANGUAGE_MALAYALAM,
			wxLANGUAGE_MALAY_BRUNEI_DARUSSALAM,
			wxLANGUAGE_MALAY_MALAYSIA,
			wxLANGUAGE_MALTESE,
			wxLANGUAGE_MANIPURI,
			wxLANGUAGE_MAORI,
			wxLANGUAGE_MARATHI,
			wxLANGUAGE_MOLDAVIAN,
			wxLANGUAGE_MONGOLIAN,
			wxLANGUAGE_NAURU,
			wxLANGUAGE_NEPALI,
			wxLANGUAGE_NEPALI_INDIA,
			wxLANGUAGE_NORWEGIAN_BOKMAL,
			wxLANGUAGE_NORWEGIAN_NYNORSK,
			wxLANGUAGE_OCCITAN,
			wxLANGUAGE_ORIYA,
			wxLANGUAGE_OROMO,
			wxLANGUAGE_PASHTO,
			wxLANGUAGE_POLISH,
			wxLANGUAGE_PORTUGUESE,
			wxLANGUAGE_PORTUGUESE_BRAZILIAN,
			wxLANGUAGE_PUNJABI,
			wxLANGUAGE_QUECHUA,
			wxLANGUAGE_RHAETO_ROMANCE,
			wxLANGUAGE_ROMANIAN,
			wxLANGUAGE_RUSSIAN,
			wxLANGUAGE_RUSSIAN_UKRAINE,
			wxLANGUAGE_SAMI,
			wxLANGUAGE_SAMOAN,
			wxLANGUAGE_SANGHO,
			wxLANGUAGE_SANSKRIT,
			wxLANGUAGE_SCOTS_GAELIC,
			wxLANGUAGE_SERBIAN,
			wxLANGUAGE_SERBIAN_CYRILLIC,
			wxLANGUAGE_SERBIAN_LATIN,
			wxLANGUAGE_SERBO_CROATIAN,
			wxLANGUAGE_SESOTHO,
			wxLANGUAGE_SETSWANA,
			wxLANGUAGE_SHONA,
			wxLANGUAGE_SINDHI,
			wxLANGUAGE_SINHALESE,
			wxLANGUAGE_SISWATI,
			wxLANGUAGE_SLOVAK,
			wxLANGUAGE_SLOVENIAN,
			wxLANGUAGE_SOMALI,
			wxLANGUAGE_SPANISH,
			wxLANGUAGE_SPANISH_ARGENTINA,
			wxLANGUAGE_SPANISH_BOLIVIA,
			wxLANGUAGE_SPANISH_CHILE,
			wxLANGUAGE_SPANISH_COLOMBIA,
			wxLANGUAGE_SPANISH_COSTA_RICA,
			wxLANGUAGE_SPANISH_DOMINICAN_REPUBLIC,
			wxLANGUAGE_SPANISH_ECUADOR,
			wxLANGUAGE_SPANISH_EL_SALVADOR,
			wxLANGUAGE_SPANISH_GUATEMALA,
			wxLANGUAGE_SPANISH_HONDURAS,
			wxLANGUAGE_SPANISH_MEXICAN,
			wxLANGUAGE_SPANISH_MODERN,
			wxLANGUAGE_SPANISH_NICARAGUA,
			wxLANGUAGE_SPANISH_PANAMA,
			wxLANGUAGE_SPANISH_PARAGUAY,
			wxLANGUAGE_SPANISH_PERU,
			wxLANGUAGE_SPANISH_PUERTO_RICO,
			wxLANGUAGE_SPANISH_URUGUAY,
			wxLANGUAGE_SPANISH_US,
			wxLANGUAGE_SPANISH_VENEZUELA,
			wxLANGUAGE_SUNDANESE,
			wxLANGUAGE_SWAHILI,
			wxLANGUAGE_SWEDISH,
			wxLANGUAGE_SWEDISH_FINLAND,
			wxLANGUAGE_TAGALOG,
			wxLANGUAGE_TAJIK,
			wxLANGUAGE_TAMIL,
			wxLANGUAGE_TATAR,
			wxLANGUAGE_TELUGU,
			wxLANGUAGE_THAI,
			wxLANGUAGE_TIBETAN,
			wxLANGUAGE_TIGRINYA,
			wxLANGUAGE_TONGA,
			wxLANGUAGE_TSONGA,
			wxLANGUAGE_TURKISH,
			wxLANGUAGE_TURKMEN,
			wxLANGUAGE_TWI,
			wxLANGUAGE_UIGHUR,
			wxLANGUAGE_UKRAINIAN,
			wxLANGUAGE_URDU,
			wxLANGUAGE_URDU_INDIA,
			wxLANGUAGE_URDU_PAKISTAN,
			wxLANGUAGE_UZBEK,
			wxLANGUAGE_UZBEK_CYRILLIC,
			wxLANGUAGE_UZBEK_LATIN,
			wxLANGUAGE_VALENCIAN,
			wxLANGUAGE_VIETNAMESE,
			wxLANGUAGE_VOLAPUK,
			wxLANGUAGE_WELSH,
			wxLANGUAGE_WOLOF,
			wxLANGUAGE_XHOSA,
			wxLANGUAGE_YIDDISH,
			wxLANGUAGE_YORUBA,
			wxLANGUAGE_ZHUANG,
			wxLANGUAGE_ZULU,

			// User's default/preffered language as got from OS.
			wxLANGUAGE_DEFAULT = wxLANGUAGE_ENGLISH_US,
		};

		// Function name   : SetLanguageDir
		// Description     : 设置多语言所在的根目录
		// Return type     : bool					false 失败 true 成功
		// Argument        : const TCHAR * path		文件夹全路径字符串
		// 
		// Writer          : 昌敦雄
		// Date            : 2011-6-14
		// Remark          : 

		GETTEXT_API bool SetLanguageDir( const TCHAR * path );

		// Function name   : SetDomain
		// Description     : 设置多语言文件名( 不含后缀名 默认后缀名为 .xml )
		// Return type     : void 
		// Argument        : const TCHAR * domain	文件名
		// 
		// Writer          : 昌敦雄
		// Date            : 2011-6-14
		// Remark          : 

		GETTEXT_API void SetDomain( const TCHAR * domain );

		// Function name   : SetLocal
		// Description     : 设置多语言类型 语言的选择
		// Return type     : void 
		// Argument        : unsigned short type	语言类型
		// 
		// Writer          : 昌敦雄
		// Date            : 2011-6-14
		// Remark          : 

		GETTEXT_API void SetLocal( unsigned short type );

		// Function name   : gettext
		// Description     : 获取翻译的字符串
		// Return type     : CONST TCHAR*	翻译后的字符串
		// Argument        : TCHAR * str	传入的原始字符串
		// 
		// Writer          : 昌敦雄
		// Date            : 2011-6-14
		// Remark          : 

		GETTEXT_API const TCHAR* gettext(const TCHAR * str);

#ifdef __cplusplus
	}
}
#endif

#endif	/*__GETTEXT_H__*/